django_blog/blog/urls.py
from django.urls import path

from .views import AuthorListView, PostDetailView, PostCreateView, \
    CategoryListView, CategoryAddView, PostUpdateView, PostDeleteView

app_name = 'blog'


urlpatterns = [
    path(r'/?P<slug>/', PostDetailView.as_view(), name='post_detail'),
    path('create/', PostCreateView.as_view(), name='post_new'),
    path('category/<pk>/', CategoryListView.as_view(), name='category_list'),
    path('add_category/', CategoryAddView.as_view(), name='add_category'),
    path('author/<author_pk>/', AuthorListView.as_view(), name='author_list'),
    path('<slug>/edit/', PostUpdateView.as_view(), name='post_edit'),
    path('<slug>/delete/', PostDeleteView.as_view(), name='post_delete')
]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from blog import views as blog_views
from blog.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('blog/post/', include('blog.urls')),
    path('users/', include('users.urls'))
]

django_blog/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'


urlpatterns = [
    url('signup/', views.signup, name='signup'),
    url('login/', views.login, name='login'),
    url('logout/', views.logout, name='logout'),
]

django_blog/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_new')


class Post(models.Model):
    title = models.CharField(max_length=100, unique=True)
    category = models.ManyToManyField(Category)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, default=True, null=True)
    post_time = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=100, allow_unicode=True, default=None, null=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(self.title, allow_unicode=True)
            default_len = len(slug)
            number = 1
            while True:
                try:
                    post = Post.objects.get(slug=slug)
                    if post == self:
                        self.slug = slug
                        break
                    else:
                        slug = slug[:default_len] + f'_{number}'
                        number += 1
                except:
                    self.slug = slug
                    break
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}--{self.post_time.strftime("%m/%d/%Y, %H:%M:%S")}'

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['title']

django_blog/users/models.py
from django.db import models

# Create your models here.

django_blog/blog/forms.py
from django import forms
from .models import Post, Category


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'category')


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)

django_blog/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

django_blog/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import generic

from .forms import PostForm, CategoryForm


from blog.models import Post, Category
# Create your views here.


class HomeView(generic.ListView):
    template_name = 'blog/base.html'
    context_object_name = 'post_list'
    model = Post
    queryset = Post.objects.filter(
            post_time__lte=timezone.now()).order_by('post_time')

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    slug_url_kwarg = 'slug'
    query_pk_and_slug = True


class CategoryListView(generic.ListView):
    template_name = 'blog/category_list.html'
    model = Category

    def get_queryset(self):
        return Category.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['post_list'] = Post.objects.filter(
            category=self.kwargs['pk']).order_by('post_time')
        context['category_list'] = Category.objects.all()
        return context


class AuthorListView(generic.ListView):
    model = User
    template_name = 'blog/author_posts.html'

    def get_queryset(self):
        return Post.objects.filter(
            author=self.kwargs['author_pk']).order_by('post_time')


class CategoryAddView(LoginRequiredMixin,
                      PermissionRequiredMixin,
                      generic.CreateView):
    model = Category
    template_name = 'blog/add_category.html'
    form_class = CategoryForm
    permission_required = 'admin'


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    template_name = 'blog/post_new.html'
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin,
                     generic.UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'blog/post_edit.html'


class PostDeleteView(LoginRequiredMixin,
                     generic.DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('home')

django_blog/users/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.shortcuts import render, redirect

from users.forms import RegisterForm


def signup(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    form = RegisterForm()
    return render(request, 'users/signup.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('home')
    form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})


def logout(request):
    auth_logout(request)
    return redirect('home')

django_blog/blog/templates/blog/add_category.html
{% extends 'blog/base.html'%}
{% block title %}
  <title>New Category</title>
{% endblock %}
{% block content %}
<form method="post" class="form border border-dark bg-dark text-white-50 p-3 mt-2 mb-2 w-25 h-auto ">
  {% csrf_token %}
  <label>Category Name</label>
  {{ form.name }}
  <button type="submit" class="save btn btn-success">Save</button>
</form>
{% endblock %}

django_blog/blog/templates/blog/author_posts.html
{% extends 'blog/base.html'%}
{% block title %}
  <title>All posts by {{ user }}</title>
{% endblock %}

{% block content %}
<h5>
  <a href="{% url 'home' %}">Return</a>
</h5>
<div class="card-columns">
  {% for post in author_posts %}
  <div class="card text-white-50 bg-dark border-dark mt-1 mb-3 p-2">
    <h3 class="card-title text-center">Title:
      a class="text-light"href="{% url 'blog:post_detail' slug=post.slug %}">
        {{ post.title }}
      </a>
    </h3>
    <h3>Category:{% for cat in post.category.all %}
      <a class="text-light" href="{% url 'blog:category_list' pk=cat.pk %}" >
        {{ cat }}
        {% endfor %}</a>
    </h3>
    <p class="text-left">Date:
      {{ post.post_time }}
    </p>
    {% if user == post.author %}
    <button type="button" class="btn btn-danger">
      <p><a href="{% url 'blog:post_edit' slug=post.slug %}" class="text-black-50">
        Edit
      </a></p>
    </button>
    <button type="button" class="btn btn-warning">
      <p><a href="{% url 'blog:post_delete' slug=post.slug %}" class="text-black-50">
        Delete
      </a></p>
    </button>
    {% endif %}
  </div>
  {% endfor %}
</div>
{% endblock %}

django_blog/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block title %}
    {% endblock %}
    <title>Main Page</title>
    <link rel="shortcut icon" type="image/jpg" href="{% static 'images/listia-osen-makro.jpg' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/main.css' %}" />
</head>
<body>
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
      <li class="navbar-brand text-blue-50">
        <h3>Welcome: {{ user }}</h3>
      </li>
      {% endif %}
        {% if user.is_authenticated %}
      <li class="nav-item ">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            <a class="nav-link" href="{% url 'blog:author_list' author_pk=user.id %}">Review posts</a>
        </button>
      </li>
      <li class="nav-item">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            <a class="nav-link" href="{% url 'blog:post_new' %}">Add new post</a>
        </button>
      </li>
      <form class="form-inline my-2 my-lg-0">
        <button class="btn btn-danger" type="submit">
            <a class="nav-link text-white" href="{% url 'users:logout' %}">Exit</a>
        </button>
      </form>
      {% else %}
      <li class="nav-item">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            <a class="text-light" href="{% url 'users:login' %}">Login</a>
        </button>
      </li>
      <li class="nav-item">
        <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">
            <a class="text-light" href="{% url 'users:signup' %}">Register</a>
        </button>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="navbar-brand text-white-50">Category:</a>
      </li>
    {% for category in category_list%}
      <li class="nav-item">
        <a class="nav-link text-light" href="{% url 'blog:category_list' pk=category.pk %}">
            {{ category }}
        </a>
      </li>
    {% endfor %}
    </ul>
  </div>
</nav>
<div class="card-columns">
    {% block home_page %}
{% for post in post_list %}
  <div class="card text-white-50 bg-dark border-dark mt-1 mb-3 p-2">
     <div class="card-header bg-transparent border-success">
       <h3 class="card-title text-center font-weight-bold ">
         <a class="text-light" href="{% url 'blog:post_detail' slug=post.slug %}">
             {{ post.title }}
         </a>
       </h3>
       <span>Category:</span>
       {% for cat in post.category.all %}
       <a class="text-light" href="{% url 'blog:category_list' pk=cat.pk %}" >
           {{ cat }}
       {% endfor %}
       </a>
     </div>
     <div class="card-body">
        <p class="card-text font-italic text-right text-truncate" style="max-width: 200px;" >
            {{ post.text }}
        </p>
     </div>
     <div class="card-footer bg-transparent border-success">
        <span>Author:</span>
       <a class="text-light" href="{% url 'blog:author_list' author_pk=post.author.pk %}">
          {{ post.author }}
       </a>
       <p>Date: {{ post.post_time }}</p>
         {% if user == post.author %}
         <button type="button" class="btn btn-danger">
             <p><a href="{% url 'blog:post_edit' slug=post.slug %}" class="text-black-50">
                 Edit
             </a></p>
         </button>
         <button type="button" class="btn btn-warning">
             <p><a href="{% url 'blog:post_delete' slug=post.slug %}" class="text-black-50">
                 Delete
             </a></p>
         </button>
         {% endif %}
     </div>
  </div>
{% endfor %}
</div>
{% block content %}
{% endblock %}
</body>
</html>

django_blog/blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% block title%}
<title>All posts: {{ category }}</title>
{% endblock %}

{% block home_page %}
<h5>
    <a href="{% url 'home'%}"><-Show All Posts</a>
</h5>
<div class="card-column">
    {% for post in post_list %}
    <div class="card text-white-50 bg-dark border-dark mt-1 mb-3 p-2">
        <h3 >Title:
            <a class="text-light" href="{% url 'blog:post_detail' slug=post.slug %}">
                {{ post.title }}
            </a>
        </h3>
        <h3>Category:
            {% for cat in post.category.all %}
            <a class="text-light"  href="{% url 'blog:category_list' pk=cat.pk %}" >
                {{ cat }}
                {% endfor %}
            </a>
        </h3>
        <h3>Author:
            <a class="text-light" href="{% url 'blog:author_list' author_pk=post.author.pk %}">
                {{ post.author }}
            </a>
        </h3>
        <p>Date: {{ post.post_time }}</p>
        {% if user == post.author %}
        <button type="button" class="btn btn-danger">
            <p><a href="{% url 'blog:post_edit' slug=post.slug %}" class="text-black-50">
                Edit
            </a></p>
        </button>
        <button type="button" class="btn btn-warning">
            <p><a href="{% url 'blog:post_delete' slug=post.slug %}" class="text-black-50">
                Delete
            </a></p>
        </button>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock %}

django_blog/blog/templates/blog/edit_post.html
{% extends 'blog/base.html' %}

{% block title %}
<title>Edit Post</title>
{% endblock %}
{% block content %}
<form method="post" class="form border border-dark bg-dark text-white-50 mt-2 p-3 mb-2 w-50 h-auto ">
  {% csrf_token %}
  {% if message %}
   {{ message }}
  {% endif %}
  <div class="form-group ">
    <label>Title</label>
    <a class="form-control-sm">
      {{ form.title }}
    </a>
  </div>
  <div class="form-group ">
    <label>Text</label>
    <a class="form-control-sm">
      {{ form.text}}
    </a>
  </div>
  <div class="form-group">
        <label>Category</label>
    <a class="form-control-sm">
      {{ form.category }}
    </a>
  </div>
  <button type="submit" class="btn btn-success">Refresh</button>
  <button type="button" class="save btn btn-warning">
    <a href="{% url 'blog:add_category' %}">Add category</a>
  </button>
</form>

{% endblock %}

django_blog/blog/templates/blog/post.html
{% extends 'blog/base.html' %}
{% block title %}
<title>Post Details {{ post.title }}</title>
{% endblock %}

{% block content %}
<h5>
    <a href="{% url 'home'%}"><-Return</a>
</h5>
<div class="card text-white-50 text-center bg-dark border-dark mb-3 p-2 w-50 h-auto">
    <h1 class="card-title">{{ post.title }}</h1>
    <h2>Category:
        {% for cat in post.category.all %}
        <a  class="text-light" href="{% url 'blog:category_list' pk=cat.pk %}" >
            {{ cat }}
        {% endfor %}
        </a>
    </h2>
    <h3 class="card-text font-italic">
        <p>{{ post.text }}</p>
    </h3>
    <h4 class="text-left"><span>Author:</span>
        <a class="text-light" href="{% url 'blog:author_list' author_pk=post.author.pk %}">
            {{ post.author }}
        </a>
    </h4>
    <p class="text-left">Date: {{ post.post_time }}</p>
    {% if user == post.author %}
         <button type="button" class="btn btn-danger">
             <p><a href="{% url 'blog:post_edit' slug=post.slug %}" class="text-black-50">
                 Edit
             </a></p>
         </button>
         <button type="button" class="btn btn-warning">
             <p><a href="{% url 'blog:post_delete' slug=post.slug %}" class="text-black-50">
                 Delete
             </a></p>
         </button>
         {% endif %}
</div>
{% endblock %}

django_blog/blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}
{% block title %}
  <title>Delete Post</title>
{% endblock %}
{% block content %}
    <form method="post" class="form border border-dark bg-dark text-white-50 p-3 mt-2 mb-2 w-25 h-auto ">
        {% csrf_token %}
      <p>Are you sure you want to delete post "{{ post.title }}"?</p>
      <input type="submit" value="Підтвердити" class="btn btn-danger" />
    </form>
{% endblock content %}

django_blog/blog/templates/blog/post_new.html
{% extends 'blog/base.html' %}
{% block title %}
<title>Create New Post</title>
{% endblock %}
{% block content %}
<form method="post" class="form border border-dark bg-dark text-white-50 mt-2 p-3 mb-2 w-50 h-auto ">
  {% csrf_token %}
  {% if message %}
   {{ message }}
  {% endif %}
  <div class="form-group ">
    <label>Title</label>
    <a class="form-control-sm">
      {{ form.title }}
    </a>
  </div>
  <div class="form-group ">
    <label>Text</label>
    <a class="form-control-sm">
      {{ form.text}}
    </a>
  </div>
  <div class="form-group">
        <label>Category</label>
    <a class="form-control-sm">
      {{ form.category }}
    </a>
  </div>
  <button type="submit" class="btn btn-success">Save</button>
  <button type="button" class="save btn btn-warning">
    <a href="{% url 'blog:add_category' %}">Add Category</a>
  </button>
</form>
{% endblock %}

django_blog/users/templates/users/login.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="shortcut icon" type="image/jpg" href="{% static 'images/listia-osen-makro.jpg' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'users/main.css' %}" />
</head>
<body>
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form action="{% url 'users:login' %}" method="post" class="form-inline">
        {% csrf_token %}
        <label class="whiteletter">Username</label>
            {{ form.username }}
        <label class="whiteletter">Password</label>
            {{ form.password }}
    <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Enter</button>
    </form>
  </div>
</nav>
</body>
</html>

django_blog/users/templates/users/signup.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    <link rel="shortcut icon" type="image/jpg" href="{% static 'images/listia-osen-makro.jpg' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'users/main.css' %}" />
</head>
<body>
<h5>
    <a class="text-light" href="{% url 'home'%}"><-Return</a>
</h5>
<form action="{% url 'users:signup' %}" method="post" class="form border border-light bg-secondary text-blue-50 mt-2 p-3 mb-2 w-100  h-150">
    {% csrf_token %}
  {{ form.non_field_errors }}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}

  <table border="1">
    {% for field in form.visible_fields %}
      <tr>
        <th>{{ field.label_tag }}</th>
        <td>
          {{ field.errors }}
          {{ field }}
          {{ field.help_text }}
        </td>
      </tr>
    {% endfor %}
  </table>
    <button type="submit" class="save btn btn-default">Register</button>
</form>
</body>
</html>